library(shiny)
library(shinydashboard)
library(DT)
library(googleVis)
library(data.table)
library(plotly)
borderF <- read.csv(file="./borderF.csv")
rownames(borderF) <- NULL
choice <- colnames(borderF)
border_choice <- unique(borderF$Border)
measure_choice <- unique(borderF$Measure)