library(shiny)
library(shinydashboard)
library(DT)
library(googleVis)
library(data.table)
library(plotly)
borderF <- read.csv(file="./borderF.csv")
rownames(borderF) <- NULL
choice <- colnames(borderF)
port_choice <-colnames(borderF$Port.Name)